# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddCamera.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(462, 382)
        Dialog.setMinimumSize(QtCore.QSize(462, 382))
        Dialog.setMaximumSize(QtCore.QSize(462, 382))
        self.buttonAddCamera = QtWidgets.QPushButton(Dialog)
        self.buttonAddCamera.setGeometry(QtCore.QRect(110, 320, 261, 51))
        self.buttonAddCamera.setMinimumSize(QtCore.QSize(261, 51))
        self.buttonAddCamera.setMaximumSize(QtCore.QSize(261, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.buttonAddCamera.setFont(font)
        self.buttonAddCamera.setObjectName("buttonAddCamera")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 260, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonRtsp = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonRtsp.setMinimumSize(QtCore.QSize(115, 22))
        self.radioButtonRtsp.setMaximumSize(QtCore.QSize(115, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonRtsp.setFont(font)
        self.radioButtonRtsp.setObjectName("radioButtonRtsp")
        self.horizontalLayout.addWidget(self.radioButtonRtsp)
        self.radioButtonHttp = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButtonHttp.setMinimumSize(QtCore.QSize(114, 22))
        self.radioButtonHttp.setMaximumSize(QtCore.QSize(114, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonHttp.setFont(font)
        self.radioButtonHttp.setObjectName("radioButtonHttp")
        self.horizontalLayout.addWidget(self.radioButtonHttp)
        self.labelProtocolType = QtWidgets.QLabel(Dialog)
        self.labelProtocolType.setGeometry(QtCore.QRect(40, 260, 111, 42))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelProtocolType.setFont(font)
        self.labelProtocolType.setObjectName("labelProtocolType")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 50, 108, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCameraName = QtWidgets.QLabel(self.layoutWidget1)
        self.labelCameraName.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraName.setFont(font)
        self.labelCameraName.setObjectName("labelCameraName")
        self.verticalLayout.addWidget(self.labelCameraName)
        self.labelCameraIP = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraIP.setFont(font)
        self.labelCameraIP.setObjectName("labelCameraIP")
        self.verticalLayout.addWidget(self.labelCameraIP)
        self.labelCameraIPAddition = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelCameraIPAddition.setFont(font)
        self.labelCameraIPAddition.setObjectName("labelCameraIPAddition")
        self.verticalLayout.addWidget(self.labelCameraIPAddition)
        self.labelUsername = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setObjectName("labelUsername")
        self.verticalLayout.addWidget(self.labelUsername)
        self.labelPassword = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout.addWidget(self.labelPassword)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 1, 441, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.labelAddCamera = QtWidgets.QLabel(self.layoutWidget2)
        self.labelAddCamera.setMinimumSize(QtCore.QSize(0, 0))
        self.labelAddCamera.setMaximumSize(QtCore.QSize(120, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelAddCamera.setFont(font)
        self.labelAddCamera.setObjectName("labelAddCamera")
        self.horizontalLayout_2.addWidget(self.labelAddCamera)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(160, 50, 263, 206))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.layoutWidget3.setFont(font)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editCameraName = QtWidgets.QLineEdit(self.layoutWidget3)
        self.editCameraName.setMinimumSize(QtCore.QSize(261, 36))
        self.editCameraName.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.editCameraName.setFont(font)
        self.editCameraName.setToolTipDuration(9999)
        self.editCameraName.setText("")
        self.editCameraName.setClearButtonEnabled(True)
        self.editCameraName.setObjectName("editCameraName")
        self.verticalLayout_2.addWidget(self.editCameraName)
        self.editCameraIP = QtWidgets.QLineEdit(self.layoutWidget3)
        self.editCameraIP.setMinimumSize(QtCore.QSize(261, 36))
        self.editCameraIP.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.editCameraIP.setFont(font)
        self.editCameraIP.setToolTipDuration(9999)
        self.editCameraIP.setText("")
        self.editCameraIP.setClearButtonEnabled(True)
        self.editCameraIP.setObjectName("editCameraIP")
        self.verticalLayout_2.addWidget(self.editCameraIP)
        self.editCameraIPAddition = QtWidgets.QLineEdit(self.layoutWidget3)
        self.editCameraIPAddition.setMinimumSize(QtCore.QSize(261, 36))
        self.editCameraIPAddition.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.editCameraIPAddition.setFont(font)
        self.editCameraIPAddition.setToolTipDuration(9999)
        self.editCameraIPAddition.setClearButtonEnabled(True)
        self.editCameraIPAddition.setObjectName("editCameraIPAddition")
        self.verticalLayout_2.addWidget(self.editCameraIPAddition)
        self.editUsername = QtWidgets.QLineEdit(self.layoutWidget3)
        self.editUsername.setMinimumSize(QtCore.QSize(261, 36))
        self.editUsername.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.editUsername.setFont(font)
        self.editUsername.setToolTipDuration(9999)
        self.editUsername.setClearButtonEnabled(True)
        self.editUsername.setObjectName("editUsername")
        self.verticalLayout_2.addWidget(self.editUsername)
        self.editPassword = QtWidgets.QLineEdit(self.layoutWidget3)
        self.editPassword.setMinimumSize(QtCore.QSize(261, 36))
        self.editPassword.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.editPassword.setFont(font)
        self.editPassword.setToolTipDuration(9999)
        self.editPassword.setClearButtonEnabled(True)
        self.editPassword.setObjectName("editPassword")
        self.verticalLayout_2.addWidget(self.editPassword)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonAddCamera.setText(_translate("Dialog", "KAMERAYI EKLE"))
        self.radioButtonRtsp.setText(_translate("Dialog", "RTSP"))
        self.radioButtonHttp.setText(_translate("Dialog", "HTTP"))
        self.labelProtocolType.setText(_translate("Dialog", "Protokol Tipi"))
        self.labelCameraName.setText(_translate("Dialog", "Kamera Adı"))
        self.labelCameraIP.setText(_translate("Dialog", "Kamera IP"))
        self.labelCameraIPAddition.setText(_translate("Dialog", "IP Ek Uzanti"))
        self.labelUsername.setText(_translate("Dialog", "Kullanıcı Adı"))
        self.labelPassword.setText(_translate("Dialog", "Şifre"))
        self.labelAddCamera.setText(_translate("Dialog", "KAMERA EKLE"))


