# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1313, 869)
        MainWindow.setMinimumSize(QtCore.QSize(1313, 869))
        MainWindow.setMaximumSize(QtCore.QSize(9999, 9999))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ComboBoxCameras = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBoxCameras.setMinimumSize(QtCore.QSize(200, 30))
        self.ComboBoxCameras.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ComboBoxCameras.setFont(font)
        self.ComboBoxCameras.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ComboBoxCameras.setMaxVisibleItems(100)
        self.ComboBoxCameras.setFrame(True)
        self.ComboBoxCameras.setObjectName("ComboBoxCameras")
        self.ComboBoxCameras.addItem("")
        self.gridLayout.addWidget(self.ComboBoxCameras, 0, 1, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(640, 279))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(640, 9999))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea_2.setFont(font)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 640, 282))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_3)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_2, 3, 0, 1, 1)
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.imgLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(False)
        font.setWeight(50)
        self.imgLabel.setFont(font)
        self.imgLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.imgLabel.setAutoFillBackground(False)
        self.imgLabel.setStyleSheet("background-color: rgb(50,50,50)\n"
"")
        self.imgLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.imgLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgLabel.setLineWidth(1)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.gridLayout.addWidget(self.imgLabel, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(640, 771))
        self.scrollArea.setMaximumSize(QtCore.QSize(9999, 9999))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(False)
        font.setWeight(50)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 645, 774))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 1, 3, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(160, 30))
        self.startButton.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color:rgb(197, 208, 255)")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setMinimumSize(QtCore.QSize(150, 30))
        self.stopButton.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setStyleSheet("background-color:rgb(197, 208, 255)")
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.detectButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detectButton.sizePolicy().hasHeightForWidth())
        self.detectButton.setSizePolicy(sizePolicy)
        self.detectButton.setMinimumSize(QtCore.QSize(150, 30))
        self.detectButton.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.detectButton.setFont(font)
        self.detectButton.setStyleSheet("background-color:rgb(197, 208, 255)")
        self.detectButton.setObjectName("detectButton")
        self.horizontalLayout.addWidget(self.detectButton)
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainButton.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.trainButton.setFont(font)
        self.trainButton.setStyleSheet("background-color:rgb(197, 208, 255)")
        self.trainButton.setObjectName("trainButton")
        self.horizontalLayout.addWidget(self.trainButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1313, 21))
        self.menubar.setObjectName("menubar")
        self.menuKameralar = QtWidgets.QMenu(self.menubar)
        self.menuKameralar.setObjectName("menuKameralar")
        self.menuFontlar = QtWidgets.QMenu(self.menubar)
        self.menuFontlar.setObjectName("menuFontlar")
        MainWindow.setMenuBar(self.menubar)
        self.actionDiskten_Ekle = QtWidgets.QAction(MainWindow)
        self.actionDiskten_Ekle.setObjectName("actionDiskten_Ekle")
        self.actionProgramHakkinda = QtWidgets.QAction(MainWindow)
        self.actionProgramHakkinda.setObjectName("actionProgramHakkinda")
        self.actionGelistiriciHakkinda = QtWidgets.QAction(MainWindow)
        self.actionGelistiriciHakkinda.setObjectName("actionGelistiriciHakkinda")
        self.actionPersonelEkle = QtWidgets.QAction(MainWindow)
        self.actionPersonelEkle.setObjectName("actionPersonelEkle")
        self.actionPersoneller = QtWidgets.QAction(MainWindow)
        self.actionPersoneller.setObjectName("actionPersoneller")
        self.actionLoglar = QtWidgets.QAction(MainWindow)
        self.actionLoglar.setObjectName("actionLoglar")
        self.actionKamera1 = QtWidgets.QAction(MainWindow)
        self.actionKamera1.setCheckable(True)
        self.actionKamera1.setObjectName("actionKamera1")
        self.actionKamera2 = QtWidgets.QAction(MainWindow)
        self.actionKamera2.setCheckable(True)
        self.actionKamera2.setObjectName("actionKamera2")
        self.actionKamera3 = QtWidgets.QAction(MainWindow)
        self.actionKamera3.setCheckable(True)
        self.actionKamera3.setObjectName("actionKamera3")
        self.actionKamera4 = QtWidgets.QAction(MainWindow)
        self.actionKamera4.setCheckable(True)
        self.actionKamera4.setObjectName("actionKamera4")
        self.actionKamera5 = QtWidgets.QAction(MainWindow)
        self.actionKamera5.setCheckable(True)
        self.actionKamera5.setObjectName("actionKamera5")
        self.actionCikis = QtWidgets.QAction(MainWindow)
        self.actionCikis.setObjectName("actionCikis")
        self.actionYazdir = QtWidgets.QAction(MainWindow)
        self.actionYazdir.setObjectName("actionYazdir")
        self.actionPersonelGirisCikisBilgileri = QtWidgets.QAction(MainWindow)
        self.actionPersonelGirisCikisBilgileri.setObjectName("actionPersonelGirisCikisBilgileri")
        self.actionFotograf_Ekle = QtWidgets.QAction(MainWindow)
        self.actionFotograf_Ekle.setObjectName("actionFotograf_Ekle")
        self.actionPersonelleriExcelDosyasinaAktar = QtWidgets.QAction(MainWindow)
        self.actionPersonelleriExcelDosyasinaAktar.setObjectName("actionPersonelleriExcelDosyasinaAktar")
        self.actionGiris_Cikis_KayitlariniExcelDosyasinaAktar = QtWidgets.QAction(MainWindow)
        self.actionGiris_Cikis_KayitlariniExcelDosyasinaAktar.setObjectName("actionGiris_Cikis_KayitlariniExcelDosyasinaAktar")
        self.actionAddCamera = QtWidgets.QAction(MainWindow)
        self.actionAddCamera.setObjectName("actionAddCamera")
        self.actionCameras = QtWidgets.QAction(MainWindow)
        self.actionCameras.setObjectName("actionCameras")
        self.actionAddFont = QtWidgets.QAction(MainWindow)
        self.actionAddFont.setObjectName("actionAddFont")
        self.actionFonts = QtWidgets.QAction(MainWindow)
        self.actionFonts.setObjectName("actionFonts")
        self.menuKameralar.addAction(self.actionAddCamera)
        self.menuKameralar.addAction(self.actionCameras)
        self.menuFontlar.addAction(self.actionAddFont)
        self.menuFontlar.addAction(self.actionFonts)
        self.menubar.addAction(self.menuKameralar.menuAction())
        self.menubar.addAction(self.menuFontlar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plaka Takip"))
        self.ComboBoxCameras.setItemText(0, _translate("MainWindow", "Kamera-1"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Okunan Plaka"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Saat"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Gorunen Plaka"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Saat"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Kamera"))
        self.startButton.setText(_translate("MainWindow", "Kamerayi Baslat"))
        self.stopButton.setText(_translate("MainWindow", "Kamerayi Durdur"))
        self.detectButton.setText(_translate("MainWindow", "Plaka Tanımayı Baslat"))
        self.trainButton.setText(_translate("MainWindow", "KNN Çalıstır"))
        self.menuKameralar.setTitle(_translate("MainWindow", "Kameralar"))
        self.menuFontlar.setTitle(_translate("MainWindow", "Fontlar"))
        self.actionDiskten_Ekle.setText(_translate("MainWindow", "Diskten Ekle"))
        self.actionProgramHakkinda.setText(_translate("MainWindow", "Program Hakkinda"))
        self.actionGelistiriciHakkinda.setText(_translate("MainWindow", "Gelistirici Hakkinda"))
        self.actionPersonelEkle.setText(_translate("MainWindow", "Personel Ekle"))
        self.actionPersoneller.setText(_translate("MainWindow", "Personeller"))
        self.actionLoglar.setText(_translate("MainWindow", "Genel Loglar"))
        self.actionKamera1.setText(_translate("MainWindow", "Kamera-1"))
        self.actionKamera2.setText(_translate("MainWindow", "Kamera-2"))
        self.actionKamera3.setText(_translate("MainWindow", "Kamera-3"))
        self.actionKamera4.setText(_translate("MainWindow", "Kamera-4"))
        self.actionKamera5.setText(_translate("MainWindow", "Kamera-5"))
        self.actionCikis.setText(_translate("MainWindow", "Cikis"))
        self.actionYazdir.setText(_translate("MainWindow", "Excel\'e Yazdir"))
        self.actionPersonelGirisCikisBilgileri.setText(_translate("MainWindow", "Personel Giris/Cikis Bilgileri"))
        self.actionFotograf_Ekle.setText(_translate("MainWindow", "Fotograf Ekle"))
        self.actionPersonelleriExcelDosyasinaAktar.setText(_translate("MainWindow", "Personelleri Excel Dosyasina Aktar"))
        self.actionGiris_Cikis_KayitlariniExcelDosyasinaAktar.setText(_translate("MainWindow", "Giris-Cikis Kayitlarini Excel Dosyasina Aktar"))
        self.actionAddCamera.setText(_translate("MainWindow", "Kamera Ekle"))
        self.actionCameras.setText(_translate("MainWindow", "Kameralar"))
        self.actionAddFont.setText(_translate("MainWindow", "Font Ekle"))
        self.actionFonts.setText(_translate("MainWindow", "Fontlar"))


